In [2]:
import os
import pandas as pd
from sqlalchemy import create_engine, text
from dotenv import load_dotenv

In [3]:
load_dotenv()

DB_URL = os.getenv("DATABASE_URL")

engine = create_engine(DB_URL)

In [4]:
df = pd.read_sql("""
SELECT * 
FROM course_data.students;
""",
engine
)

In [5]:
df.head(10)

   student_no student_name  age
0           1      Michael   19
1           2         Doug   18
2           3     Samantha   21
3           4         Pete   20
4           5        Ralph   19
5           6       Arnold   22
6           7      Michael   19
7           8         Jack   19
8           9         Rand   17
9          10       Sylvia   20

In [6]:
students = pd.read_sql(
    "SELECT * FROM course_data.students;",
    engine
)

courses = pd.read_sql(
    "SELECT * FROM course_data.courses;",
    engine
)

student_enrollment = pd.read_sql(
    "SELECT * FROM course_data.student_enrollment;",
    engine
)

professors = pd.read_sql(
    "SELECT * FROM course_data.professors;",
    engine
)

teach = pd.read_sql(
    "SELECT * FROM course_data.teach;",
    engine
)

In [7]:
students.head(10)

   student_no student_name  age
0           1      Michael   19
1           2         Doug   18
2           3     Samantha   21
3           4         Pete   20
4           5        Ralph   19
5           6       Arnold   22
6           7      Michael   19
7           8         Jack   19
8           9         Rand   17
9          10       Sylvia   20

In [8]:
professors.head(10)

  last_name   department  salary   hire_date
0     Chong      Science   88000  2006-04-18
1     Brown         Math   97000  2002-08-22
2     Jones      History   67000  2009-11-17
3    Wilson    Astronomy  110000  2005-01-15
4    Miller  Agriculture   82000  2008-05-08
5  Williams          Law  105000  2001-06-05